on: [push]
name: Default
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Go version
      run: go version
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: go build -ldflags="-s -w" -v
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: tars-discord
        path: tars-discord
