on: [push]
name: Default
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    - name: Go version
      run: go version
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build
      run: go build -ldflags="-s -w" -v
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: tars-discord
        path: tars-discord
